version: "4"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container_orders
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./docker/pgsql/init.sql:/docker-entrypoint-initdb.d/init.sql
